# Model arguments
# model_name_or_path: alignment-handbook/zephyr-7b-sft-lora
model_name_or_path: /opt/ml/output/model/sft
torch_dtype: auto
use_flash_attention_2: true

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# Data training arguments

dataset_mixer:
  /opt/ml/input/data/train/dpo_split: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 2

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: epoch
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: zephyr-7b-dpo-lora
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 3
optim: rmsprop
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "no"
save_total_limit: null
seed: 42
output_dir: /opt/ml/output/model/dpo
warmup_ratio: 0.1
logging_dir: "/opt/ml/output/tensorboard"
report_to:
- tensorboard